### PR TITLE
fix(lsp): Ensure custom LSP configs are used

### LINKED ISSUE #93: Bug? Custom lsp options not used
It seems that after https://github.com/Alexis12119/nvim-config/commit/8ca206c606962164bae02e3d368b71424c08ff54 , options in `plugins.lsp.opts` are not used in lsp config anymore. E.g. custom keymaps are no longer available, semanticTokens are now enabled, etc.

### PR DESCRIPTION
**Pull request by serpro69**
Fix #93

### CODE REVIEW

File: lua/plugins/lsp/configs/mason.lua [hunk 1]
```diff
@@ -42,11 +42,7 @@ return {
       mason_lspconfig.setup {
         ensure_installed = {},
         automatic_enable = {
-          exclude = {
-            "jdtls",
-            "rust_analyzer",
-            "ts_ls",
-          },
```
Comment (serpro69) [inline lua/plugins/lsp/configs/mason.lua:49]: Removed this because the idea is to configure all servers that one has installed. If one doesn't want to enable some servers, then why install them in the first place? 🤷 Don't know what was your thinking behind this exclude rule, can re-add it if you feel it's needed :)

Comment (Alexis12119) [reply lua/plugins/lsp/configs/mason.lua:49]: LOL, that's true, but typescript-tools needed `ts_ls`.

**Comment by Alexis12119** [comment]
@serpro69 Can you undo the changes on the `exclude` part. `nvim-jdtls` needed `jdtls` and `typescript-tools` needed `ts_ls` and it's fine to remove the `rust_analyzer`. Thanks.

File: lua/plugins/lsp/configs/mason.lua (hunk 1 above)
Comment (serpro69) [reply lua/plugins/lsp/configs/mason.lua]: Hmm, right. I stopped using typescript-tools due to some bugs I can't live with 😁 Though, if you're using typescript-tools, do you still need to install ts_ls? If it's not installed - it's not enabled, right? Although I guess in this case it's better to be explicit and disable it, I agree 👍

**Comment by serpro69** [comment]
> @serpro69 Can you undo the changes on the `exclude` part? `nvim-jdtls` needed `jdtls` and `typescript-tools` needed `ts_ls` and it's fine to remove the `rust_analyzer`. Thanks.

Done.

**Comment by Alexis12119** [comment]
Thank you very much.
